### ISSUE TITLE
atom-gedit-syntax obscures bracket highlighting

### ISSUE THREAD

**Issue by jdpipe** [Emonadeo/atom-gedit-syntax#1]
this theme hides the bracket highlighting of atom. not sure why, but when reverting to 'atom-light' theme, everything worked much better.
note that I had the 'highlight current line' option selected.

**Comment by emonadeo** [comment]
Thanks for reporting. I noticed that the background renders above the bracket highlighting. Looking at the official atom themes I changed the line highlighting to be transparent instead of solid. As a side effect the grid now is also visible on the selected line.

**Comment by jdpipe** [comment]
thanks for looking at this! I took another look though, and it's still not working for me. Please note that I have the "highlight current line" option selected. You can see a tiny bit of the highlight poking out from beneath the line highlight, but that's all.

![image](https://user-images.githubusercontent.com/87423/66712778-112a9900-eda2-11e9-8dfe-6b1fd81ca50c.png)

**Comment by emonadeo** [comment]
The underline is actually intended behavior but I agree, it's hard to see. I actually didn't know Atom also supported block highlighting rather than underline highlight. See example below. 

One Light:
![image](https://user-images.githubusercontent.com/13782948/66820545-2c7fda80-ef41-11e9-95ca-d54a213704e0.png)

Atom Light:
![image](https://user-images.githubusercontent.com/13782948/66820684-7668c080-ef41-11e9-967b-d48ce6ef7952.png)

Will fix.

**Comment by jdpipe** [comment]
Great! thanks for that. FWIW here is how Gedit does it:

![image](https://user-images.githubusercontent.com/87423/67341570-4d8f8f00-f530-11e9-8568-e1a4393ebdd0.png)
